"""Build the Worker parser from the canonical Python parser without server imports.

Run before deploying, or use --check in CI. Existing Vercel and desktop entrypoints
remain the source of truth; this copies their pure parsing definitions verbatim.
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "api/python_parse.py"
DESTINATION = Path(__file__).resolve().parent / "src/parser_core.py"
ALLOWED_IMPORTS = {"__future__", "html", "json", "re", "typing", "urllib.parse"}


def render() -> str:
    source = SOURCE.read_text(encoding="utf-8")
    lines = source.splitlines(keepends=True)
    parts = [
        '# Generated by cloudflare/python/sync_core.py; edit api/python_parse.py.\n',
        '# Only the platform-independent parser is copied; network I/O uses Workers fetch.\n\n',
    ]
    for node in ast.parse(source).body:
        if isinstance(node, ast.ClassDef) and node.name == "SafeRedirectHandler":
            break
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            continue
        if isinstance(node, ast.Import):
            if any(item.name not in ALLOWED_IMPORTS for item in node.names):
                continue
        if isinstance(node, ast.ImportFrom) and node.module not in ALLOWED_IMPORTS:
            continue
        parts.append("".join(lines[node.lineno - 1:node.end_lineno]).rstrip() + "\n\n")
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not DESTINATION.exists() or DESTINATION.read_text(encoding="utf-8") != expected:
            parser.exit(1, "Python Worker parser is stale; run python3 cloudflare/python/sync_core.py\n")
        print("Python Worker parser matches api/python_parse.py")
        return
    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    # Wrangler watches bundled modules. Rewriting an unchanged generated file
    # would trigger another build indefinitely during local development.
    if not DESTINATION.exists() or DESTINATION.read_text(encoding="utf-8") != expected:
        DESTINATION.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
