# Generated by cloudflare/python/sync_core.py; edit api/python_parse.py.
# Only the platform-independent parser is copied; network I/O uses Workers fetch.

from __future__ import annotations

import html as html_lib

import json

import re

from typing import Any, Iterable

from urllib.parse import quote, unquote, urljoin, urlparse

URL_PATTERN = re.compile(r"https?://[^\s<>'\"()[\]{}，。！？、]+", re.I)

MARKDOWN_URL_PATTERN = re.compile(r"\]\(\s*(https?://[^)\s<>]+)\s*\)", re.I)

MARKDOWN_ESCAPE_PATTERN = re.compile(r"\\([^A-Za-z0-9\s])")

XHS_IMAGE_PATTERN = re.compile(
    r"https?:(?:(?:\\u002[fF])|(?:\\/)|/){2}"
    r"[^\"'<>\\\s]+?(?:xhscdn\.com|ci\.xiaohongshu\.com)"
    r"[^\"'<>\\\s]*",
    re.I,
)

HIGH_QUALITY_PATTERN = re.compile(
    r"!nd_dft_wlteh_(?:webp|jpg|jpeg|png)_3(?:$|[?#])",
    re.I,
)

NOTE_ID_PATTERN = re.compile(
    r"/(?:discovery/item|explore|item)/([A-Za-z0-9_-]{12,64})(?:/|$)",
    re.I,
)

IMAGE_LIST_KEY_PATTERN = re.compile(r'["\']imageList["\']\s*:\s*\[')

INITIAL_STATE_PATTERN = re.compile(r"(?:window\.)?__INITIAL_STATE__\s*=\s*")

INITIAL_STATE_SCRIPT_PATTERN = re.compile(
    r"<script\b[^>]*\bid=[\"']__INITIAL_STATE__[\"'][^>]*>"
    r"([\s\S]*?)</script>",
    re.I,
)

PAGE_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) "
        "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 "
        "Mobile/15E148 Safari/604.1"
    ),
    "Accept": (
        "text/html,application/xhtml+xml,application/xml;q=0.9,"
        "image/avif,image/webp,image/apng,*/*;q=0.8"
    ),
    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.7",
    "Cache-Control": "no-cache",
    "Pragma": "no-cache",
}

DIRECT_IMAGE_HOSTS = {
    "sns-webpic-qc.xhscdn.com",
    "sns-webpic.xhscdn.com",
    "sns-img-hw.xhscdn.com",
    "sns-img-bd.xhscdn.com",
    "sns-img-al.xhscdn.com",
    "ci.xiaohongshu.com",
}

IMAGE_LIST_KEYS = ("imageList", "image_list", "images")

NOTE_WRAPPER_KEYS = ("note", "noteData", "note_data", "data")

VIDEO_STREAM_KEYS = ("h264", "h265", "h266", "av1")

VIDEO_META_KEYS = {
    "og:video",
    "og:video:url",
    "og:video:secure_url",
    "twitter:player:stream",
}

MAX_HTML_BYTES = 6 * 1024 * 1024

MAX_INPUT_LENGTH = 3000

class XhsError(RuntimeError):
    def __init__(self, message: str, status_code: int = 400) -> None:
        super().__init__(message)
        self.status_code = status_code

def normalize_image_url(raw: Any) -> str:
    value = html_lib.unescape(str(raw or "").strip().strip("\"'"))
    replacements = {
        "\\u002F": "/",
        "\\u002f": "/",
        "\\u0026": "&",
        "\\u003D": "=",
        "\\u003d": "=",
        "\\x26": "&",
        "\\/": "/",
    }
    for old, new in replacements.items():
        value = value.replace(old, new)
    value = value.rstrip("\\")
    if value.startswith("//"):
        value = "https:" + value
    if value.startswith("http://"):
        value = "https://" + value[len("http://") :]
    return value

def is_xhs_image_url(value: Any) -> bool:
    try:
        parsed = urlparse(normalize_image_url(value))
        port = parsed.port
    except ValueError:
        return False
    host = (parsed.hostname or "").lower()
    return bool(
        parsed.scheme == "https"
        and not parsed.username
        and not parsed.password
        and port in (None, 443)
        and (
            host == "xhscdn.com"
            or host.endswith(".xhscdn.com")
            or host == "ci.xiaohongshu.com"
        )
    )

def is_direct_image_url(value: str) -> bool:
    normalized = normalize_image_url(value)
    try:
        parsed = urlparse(normalized)
    except ValueError:
        return False
    return bool(
        is_xhs_image_url(normalized)
        and (parsed.hostname or "").lower() in DIRECT_IMAGE_HOSTS
    )

def is_xhs_video_url(value: Any) -> bool:
    try:
        parsed = urlparse(normalize_image_url(value))
        port = parsed.port
    except ValueError:
        return False
    host = (parsed.hostname or "").lower()
    return bool(
        parsed.scheme == "https"
        and not parsed.username
        and not parsed.password
        and port in (None, 443)
        and (host == "xhscdn.com" or host.endswith(".xhscdn.com"))
        and len(parsed.path) > 1
    )

def is_allowed_page_host(hostname: str | None) -> bool:
    host = (hostname or "").lower().rstrip(".")
    return (
        host == "xhslink.com"
        or host.endswith(".xhslink.com")
        or host == "xhslink.cn"
        or host.endswith(".xhslink.cn")
        or host == "xiaohongshu.com"
        or host.endswith(".xiaohongshu.com")
    )

def is_allowed_page_url(value: str) -> bool:
    try:
        parsed = urlparse(value)
        port = parsed.port
    except ValueError:
        return False
    return bool(
        parsed.scheme.lower() == "https"
        and not parsed.username
        and not parsed.password
        and port in (None, 443)
        and is_allowed_page_host(parsed.hostname)
    )

def extract_input_url(text: str) -> str:
    input_text = text.strip()
    candidates = MARKDOWN_URL_PATTERN.findall(input_text)
    candidates.extend(match.group(0) for match in URL_PATTERN.finditer(input_text))
    if not candidates:
        raise XhsError("没有检测到有效链接，请粘贴小红书分享文案或链接。")

    found_parsed_url = False
    for candidate in dict.fromkeys(candidates):
        markdown_unescaped = MARKDOWN_ESCAPE_PATTERN.sub(r"\1", candidate)
        value = normalize_image_url(
            markdown_unescaped.rstrip(".,;:!?)]}，。！？；：）】》")
        )
        try:
            parsed = urlparse(value)
        except ValueError:
            continue
        if not parsed.scheme or not parsed.netloc:
            continue
        found_parsed_url = True

        if is_allowed_page_url(value) or is_xhs_image_url(value):
            return value

    if not found_parsed_url:
        raise XhsError("链接格式无效。")
    raise XhsError("只支持小红书分享链接或小红书图片链接。")

def extract_note_id(value: str) -> str | None:
    try:
        path = urlparse(value).path
    except ValueError:
        return None
    match = NOTE_ID_PATTERN.search(path)
    return match.group(1) if match else None

def unique_keep_order(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in values:
        normalized = normalize_image_url(item).split("#", 1)[0]
        if not is_xhs_image_url(normalized) or normalized in seen:
            continue
        seen.add(normalized)
        result.append(normalized)
    return result

def image_quality_score(url: str) -> int:
    lower = normalize_image_url(url).lower()
    score = 0
    if HIGH_QUALITY_PATTERN.search(lower):
        score += 10000
    if "!nd_dft_" in lower:
        score += 5000
    if "_wlteh_webp_3" in lower:
        score += 3000
    if re.search(r"_(?:webp|jpg|jpeg|png)_3(?:$|[?#])", lower):
        score += 1500
    if "sns-webpic-qc.xhscdn.com" in lower:
        score += 600
    if "sns-img-" in lower or "ci.xiaohongshu.com" in lower:
        score += 500

    penalties = {
        "!nd_prv_": 7000,
        "preview": 5000,
        "thumbnail": 5000,
        "thumb": 4000,
        "_mw_1": 4500,
        "_webp_1": 3500,
        "_webp_2": 2500,
        "/avatar/": 10000,
        "avatar": 8000,
        "/head/": 8000,
    }
    for token, penalty in penalties.items():
        if token in lower:
            score -= penalty
    return score

def collect_urls(value: Any) -> list[str]:
    found: list[str] = []
    if isinstance(value, str):
        if is_xhs_image_url(value):
            found.append(value)
    elif isinstance(value, list):
        for item in value:
            found.extend(collect_urls(item))
    elif isinstance(value, dict):
        for item in value.values():
            found.extend(collect_urls(item))
    return found

def collect_urls_for_keys(value: Any, keys: set[str]) -> list[str]:
    found: list[str] = []
    if isinstance(value, list):
        for item in value:
            found.extend(collect_urls_for_keys(item, keys))
    elif isinstance(value, dict):
        for key, item in value.items():
            if key in keys:
                found.extend(collect_urls(item))
        for item in value.values():
            if isinstance(item, (list, dict)):
                found.extend(collect_urls_for_keys(item, keys))
    return found

def choose_one_url_per_image(image_list: Any) -> list[str]:
    if not isinstance(image_list, list):
        return []

    default_keys = {
        "urlDefault",
        "url_default",
        "defaultUrl",
        "default_url",
        "originUrl",
        "origin_url",
        "original",
        "originalUrl",
        "original_url",
    }
    normal_keys = {"url", "imageUrl", "image_url", "fileUrl", "file_url"}
    preview_keys = {
        "urlPre",
        "url_pre",
        "previewUrl",
        "preview_url",
        "thumbnail",
        "thumbnailUrl",
        "thumbnail_url",
    }

    selected: list[str] = []
    for item in image_list:
        defaults = unique_keep_order(collect_urls_for_keys(item, default_keys))
        normals = unique_keep_order(collect_urls_for_keys(item, normal_keys))
        previews = unique_keep_order(collect_urls_for_keys(item, preview_keys))
        all_urls = unique_keep_order(collect_urls(item))
        candidates = unique_keep_order(defaults + normals + all_urls + previews)
        if candidates:
            selected.append(max(candidates, key=image_quality_score))
    return unique_keep_order(selected)

def is_live_photo_item(item: Any) -> bool:
    if not isinstance(item, dict):
        return False

    def enabled(value: Any) -> bool:
        if value is True or value == 1:
            return True
        return isinstance(value, str) and value.strip().lower() in {"1", "true"}

    return any(
        enabled(item.get(key))
        for key in ("livePhoto", "live_photo", "isLivePhoto", "is_live_photo")
    )

def choose_image_assets(image_list: Any) -> list[dict[str, Any]]:
    """按 imageList 顺序保留静态图及同项实况动态流。"""
    if not isinstance(image_list, list):
        return []

    assets: list[dict[str, Any]] = []
    for item in image_list:
        # stream 里的 MP4 同样位于 xhscdn.com，选静态图时必须排除这些字段。
        image_only_item = (
            {
                key: value
                for key, value in item.items()
                if key not in {"stream", "livePhotoStream", "live_photo_stream"}
            }
            if isinstance(item, dict)
            else item
        )
        urls = choose_one_url_per_image([image_only_item])
        if not urls:
            continue

        stream_root = None
        if isinstance(item, dict):
            stream_root = next(
                (
                    value
                    for value in (
                        item.get("stream"),
                        item.get("livePhotoStream"),
                        item.get("live_photo_stream"),
                    )
                    if isinstance(value, dict) and value
                ),
                None,
            )
        live_streams = extract_streams_from_root(
            stream_root,
            "live-photo-stream",
        )
        assets.append(
            {
                "sourceUrl": urls[0],
                "livePhoto": is_live_photo_item(item) or bool(live_streams),
                "liveVideo": live_streams[0] if live_streams else None,
            }
        )

    # 不按 URL 或 token 去重：相同静态图也可能配有不同动态流。
    return assets

def normalize_number(value: Any) -> int:
    try:
        number = int(float(value or 0))
    except (TypeError, ValueError, OverflowError):
        return 0
    return number if number > 0 else 0

def collect_video_urls_from_stream(stream: Any) -> list[str]:
    if not isinstance(stream, dict):
        return []

    values: list[Any] = [
        stream.get("masterUrl"),
        stream.get("master_url"),
        stream.get("url"),
    ]
    for key in ("masterUrls", "master_urls", "backupUrls", "backup_urls"):
        item = stream.get(key)
        if isinstance(item, list):
            values.extend(item)

    seen: set[str] = set()
    urls: list[str] = []
    for value in values:
        if not isinstance(value, str):
            continue
        normalized = normalize_image_url(value).split("#", 1)[0]
        if not is_xhs_video_url(normalized) or normalized in seen:
            continue
        seen.add(normalized)
        urls.append(normalized)
    return urls

def codec_priority(codec: Any) -> int:
    normalized = str(codec or "").lower()
    if "264" in normalized or normalized == "avc":
        return 4
    if "265" in normalized or "hevc" in normalized:
        return 3
    if "266" in normalized or "vvc" in normalized:
        return 2
    if "av1" in normalized:
        return 1
    return 0

def video_quality_score(video: dict[str, Any]) -> int:
    return (
        (2 if video.get("hasAudio") is True else 0 if video.get("hasAudio") is False else 1) * 10**18
        + codec_priority(video.get("codec")) * 10**15
        + normalize_number(video.get("width"))
        * normalize_number(video.get("height"))
        * 10**6
        + normalize_number(video.get("bitrate")) * 10
        + normalize_number(video.get("size"))
    )

def stream_audio_metadata(item: dict[str, Any]) -> dict[str, Any]:
    codec = str(item.get("audioCodec") or item.get("audio_codec") or "").lower()
    channels = normalize_number(item.get("audioChannels") or item.get("audio_channels"))
    bitrate = normalize_number(item.get("audioBitrate") or item.get("audio_bitrate"))
    explicit = item.get("hasAudio", item.get("has_audio"))
    keys = ("audioCodec", "audio_codec", "audioChannels", "audio_channels", "audioBitrate", "audio_bitrate")
    has_audio = explicit if isinstance(explicit, bool) else True if channels or bitrate or codec not in ("", "none", "null", "unknown", "0") else False if any(key in item for key in keys) else None
    return {"hasAudio": has_audio, "audioCodec": codec, "audioChannels": channels, "audioBitrate": bitrate}

def extract_streams_from_root(
    stream_root: Any,
    source: str = "media-stream",
) -> list[dict[str, Any]]:
    if not isinstance(stream_root, dict):
        return []

    streams: list[dict[str, Any]] = []
    for stream_key in VIDEO_STREAM_KEYS:
        raw_streams = stream_root.get(stream_key)
        if isinstance(raw_streams, list):
            stream_list = raw_streams
        elif isinstance(raw_streams, dict):
            stream_list = [raw_streams]
        else:
            continue
        for item in stream_list:
            if not isinstance(item, dict):
                continue
            urls = collect_video_urls_from_stream(item)
            if not urls:
                continue
            codec = (
                item.get("videoCodec")
                or item.get("video_codec")
                or item.get("codec")
                or stream_key
            )
            streams.append(
                {
                    "url": urls[0],
                    "backupUrls": urls[1:],
                    "codec": str(codec).lower(),
                    "width": normalize_number(item.get("width")),
                    "height": normalize_number(item.get("height")),
                    "bitrate": normalize_number(
                        item.get("videoBitrate")
                        or item.get("video_bitrate")
                        or item.get("bitrate")
                    ),
                    "size": normalize_number(
                        item.get("size")
                        or item.get("fileSize")
                        or item.get("file_size")
                    ),
                    "duration": normalize_number(
                        item.get("videoDuration")
                        or item.get("video_duration")
                        or item.get("duration")
                    ),
                    "qualityType": str(
                        item.get("qualityType")
                        or item.get("quality_type")
                        or ""
                    ),
                    "source": source,
                    **stream_audio_metadata(item),
                }
            )

    deduped: dict[str, dict[str, Any]] = {}
    for stream in streams:
        url = str(stream.get("url") or "")
        existing = deduped.get(url)
        if existing is None or video_quality_score(stream) > video_quality_score(existing):
            deduped[url] = stream

    return sorted(deduped.values(), key=video_quality_score, reverse=True)

def extract_video_streams_from_note(note: Any) -> list[dict[str, Any]]:
    """只从当前笔记对象读取视频流，不扫描相关推荐。"""
    if not isinstance(note, dict):
        return []

    video = note.get("video")
    media = video.get("media") if isinstance(video, dict) else None
    stream_root = media.get("stream") if isinstance(media, dict) else None
    streams = extract_streams_from_root(stream_root, "media-stream")

    if isinstance(video, dict):
        consumer = video.get("consumer")
        key = None
        if isinstance(consumer, dict):
            key = consumer.get("originVideoKey") or consumer.get("origin_video_key")
        key = key or video.get("originVideoKey") or video.get("origin_video_key")
        if isinstance(key, str) and key.strip():
            clean_key = key.strip().lstrip("/")
            url = normalize_image_url(
                f"https://sns-video-bd.xhscdn.com/{clean_key}"
            )
            if is_xhs_video_url(url) and not any(stream["url"] == url for stream in streams):
                streams.append(
                    {
                        "url": url,
                        "backupUrls": [],
                        "codec": "h264",
                        "width": 0,
                        "height": 0,
                        "bitrate": 0,
                        "size": 0,
                        "qualityType": "origin",
                        "source": "origin-video-key",
                        "hasAudio": None,
                    }
                )

    return streams

def format_video_label(video: dict[str, Any], index: int) -> str:
    width = normalize_number(video.get("width"))
    height = normalize_number(video.get("height"))
    resolution = f"{width}×{height}" if width and height else "原始清晰度"
    codec = str(video.get("codec") or "video").upper()
    bitrate = normalize_number(video.get("bitrate"))
    bitrate_text = f" · {round(bitrate / 1000)} kbps" if bitrate else ""
    return f"{resolution} · {codec}{bitrate_text} · 线路 {index + 1}"

def prepare_video_results(videos: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    sorted_videos = sorted(videos, key=video_quality_score, reverse=True)[:12]
    results: list[dict[str, Any]] = []
    for index, video in enumerate(sorted_videos):
        item = dict(video)
        item["label"] = format_video_label(item, index)
        item["isDefault"] = index == 0
        results.append(item)
    return results

def extract_balanced_structure(
    text: str, start: int, open_char: str, close_char: str
) -> tuple[str, int] | None:
    if start >= len(text) or text[start] != open_char:
        return None

    depth = 0
    in_string = False
    quote_char = ""
    escape = False

    for index in range(start, len(text)):
        char = text[index]
        if in_string:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == quote_char:
                in_string = False
                quote_char = ""
            continue

        if char in {'"', "'"}:
            in_string = True
            quote_char = char
        elif char == open_char:
            depth += 1
        elif char == close_char:
            depth -= 1
            if depth == 0:
                return text[start : index + 1], index + 1
    return None

def replace_bare_js_values(text: str) -> str:
    output: list[str] = []
    index = 0
    in_string = False
    quote_char = ""
    escape = False
    token_pattern = re.compile(r"^(?:undefined|NaN|-?Infinity)\b")

    while index < len(text):
        char = text[index]
        if in_string:
            output.append(char)
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == quote_char:
                in_string = False
                quote_char = ""
            index += 1
            continue

        if char in {'"', "'"}:
            in_string = True
            quote_char = char
            output.append(char)
            index += 1
            continue

        match = token_pattern.match(text[index:])
        if match:
            output.append("null")
            index += len(match.group(0))
            continue

        output.append(char)
        index += 1
    return "".join(output)

def parse_json_like(text: str) -> Any | None:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        try:
            return json.loads(replace_bare_js_values(text))
        except json.JSONDecodeError:
            return None

def extract_initial_states(page_html: str) -> list[dict[str, Any]]:
    states: list[dict[str, Any]] = []
    seen_ranges: set[tuple[int, int]] = set()

    for match in INITIAL_STATE_PATTERN.finditer(page_html):
        start = page_html.find("{", match.end())
        if start < 0:
            continue
        balanced = extract_balanced_structure(page_html, start, "{", "}")
        if not balanced:
            continue
        structure, end = balanced
        range_key = (start, end)
        if range_key in seen_ranges:
            continue
        seen_ranges.add(range_key)
        parsed = parse_json_like(structure)
        if isinstance(parsed, dict):
            states.append(parsed)

    for match in INITIAL_STATE_SCRIPT_PATTERN.finditer(page_html):
        parsed = parse_json_like(html_lib.unescape(match.group(1).strip()))
        if isinstance(parsed, dict):
            states.append(parsed)
    return states

def object_has_target_id(value: Any, note_id: str) -> bool:
    if not isinstance(value, dict):
        return False
    identifiers = (
        value.get("noteId"),
        value.get("note_id"),
        value.get("id"),
        value.get("itemId"),
        value.get("item_id"),
    )
    return any(str(identifier or "") == note_id for identifier in identifiers)

def direct_image_list(value: Any) -> list[Any] | None:
    if not isinstance(value, dict):
        return None
    for key in IMAGE_LIST_KEYS:
        item = value.get(key)
        if isinstance(item, list):
            return item
    return None

def unwrap_note_candidates(
    value: Any, note_id: str, from_exact_map_key: bool = False
) -> list[dict[str, Any]]:
    candidates: list[dict[str, Any]] = []
    if not isinstance(value, dict):
        return candidates

    if from_exact_map_key or object_has_target_id(value, note_id):
        candidates.append(value)

    for key in NOTE_WRAPPER_KEYS:
        wrapped = value.get(key)
        if not isinstance(wrapped, dict):
            continue
        if from_exact_map_key or object_has_target_id(wrapped, note_id):
            candidates.append(wrapped)
    return candidates

def get_path(root: Any, path: tuple[str, ...]) -> Any:
    current = root
    for key in path:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current

def find_exact_note_candidates(state: dict[str, Any], note_id: str) -> list[dict[str, Any]]:
    candidates: list[dict[str, Any]] = []
    maps = (
        get_path(state, ("note", "noteDetailMap")),
        get_path(state, ("note", "noteDetailMapV2")),
        get_path(state, ("noteDetailMap",)),
        get_path(state, ("data", "noteDetailMap")),
    )

    for note_map in maps:
        if isinstance(note_map, dict) and note_id in note_map:
            candidates.extend(
                unwrap_note_candidates(note_map[note_id], note_id, True)
            )

    visited: set[int] = set()
    stack: list[tuple[Any, int]] = [(state, 0)]
    max_visited = 120000

    while stack and len(visited) < max_visited:
        value, depth = stack.pop()
        if not isinstance(value, (dict, list)) or depth > 24:
            continue
        identity = id(value)
        if identity in visited:
            continue
        visited.add(identity)

        if isinstance(value, dict):
            if object_has_target_id(value, note_id):
                candidates.extend(unwrap_note_candidates(value, note_id, False))
            if note_id in value:
                candidates.extend(
                    unwrap_note_candidates(value[note_id], note_id, True)
                )
            children = value.values()
        else:
            children = value

        for child in children:
            if isinstance(child, (dict, list)):
                stack.append((child, depth + 1))
    return candidates

def extract_title_from_note_object(value: Any) -> str:
    if not isinstance(value, dict):
        return ""
    title = value.get("title") or value.get("displayTitle") or value.get("display_title")
    return str(title).strip()[:120] if isinstance(title, str) else ""

def extract_content_from_note_object(value: Any) -> str:
    if not isinstance(value, dict):
        return ""

    # 文案必须和已经锁定的当前笔记对象同源，不能递归扫描相关推荐。
    for key in ("desc", "description"):
        content = value.get(key)
        if not isinstance(content, str) or not content.strip():
            continue
        return content.replace("\r\n", "\n").replace("\r", "\n").strip()[:10000]
    return ""

def select_exact_note_from_states(
    page_html: str, note_id: str
) -> dict[str, Any] | None:
    matches: list[dict[str, Any]] = []
    for state in extract_initial_states(page_html):
        for candidate in find_exact_note_candidates(state, note_id):
            image_list = direct_image_list(candidate)
            images = choose_image_assets(image_list) if image_list is not None else []
            videos = extract_video_streams_from_note(candidate)
            if not images and not videos:
                continue
            matches.append(
                {
                    "images": images,
                    "videos": videos,
                    "title": extract_title_from_note_object(candidate),
                    "content": extract_content_from_note_object(candidate),
                    "exact_id": object_has_target_id(candidate, note_id),
                }
            )
    if not matches:
        return None
    matches.sort(
        key=lambda item: (
            int(bool(item["exact_id"])),
            len(item["images"])
            + len(item["videos"])
            + sum(1 for image in item["images"] if image.get("liveVideo")),
            len(item["images"]),
        ),
        reverse=True,
    )
    return matches[0]

def find_image_list_arrays_with_positions(text: str) -> list[dict[str, Any]]:
    arrays: list[dict[str, Any]] = []
    for match in IMAGE_LIST_KEY_PATTERN.finditer(text):
        start = text.find("[", match.start())
        if start < 0:
            continue
        balanced = extract_balanced_structure(text, start, "[", "]")
        if balanced:
            array_text, end = balanced
            arrays.append(
                {
                    "key_start": match.start(),
                    "start": start,
                    "end": end,
                    "text": array_text,
                }
            )
    return arrays

def object_ranges_at_positions(
    text: str, positions: Iterable[int]
) -> dict[int, dict[str, int]]:
    requested = sorted(set(positions))
    owner_starts: dict[int, int] = {}
    object_ends: dict[int, int] = {}
    object_stack: list[int] = []
    requested_index = 0
    in_string = False
    quote = ""
    escape = False

    for index, char in enumerate(text):
        while requested_index < len(requested) and requested[requested_index] < index:
            requested_index += 1
        while requested_index < len(requested) and requested[requested_index] == index:
            if not in_string and object_stack:
                owner_starts[index] = object_stack[-1]
            requested_index += 1

        if in_string:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == quote:
                in_string = False
                quote = ""
            continue

        if char in {'"', "'"}:
            in_string = True
            quote = char
        elif char == "{":
            object_stack.append(index)
        elif char == "}" and object_stack:
            start = object_stack.pop()
            object_ends[start] = index + 1

    ranges: dict[int, dict[str, int]] = {}
    for position, start in owner_starts.items():
        end = object_ends.get(start)
        if end is not None and end > position:
            ranges[position] = {"start": start, "end": end}
    return ranges

def target_note_object_ranges(text: str, note_id: str) -> list[dict[str, int]]:
    pattern = re.compile(
        r'["\'](?:noteId|note_id)["\']\s*:\s*(["\'])'
        r'([A-Za-z0-9_-]{12,64})\1'
    )
    anchors = [
        match.start()
        for match in pattern.finditer(text)
        if match.group(2) == note_id
    ]
    ranges_by_anchor = object_ranges_at_positions(text, anchors)
    ranges: list[dict[str, int]] = []
    seen: set[tuple[int, int]] = set()
    for anchor in anchors:
        object_range = ranges_by_anchor.get(anchor)
        if not object_range:
            continue
        key = (object_range["start"], object_range["end"])
        if key in seen:
            continue
        seen.add(key)
        ranges.append({**object_range, "anchor": anchor})
    return ranges

def target_owner_anchors(
    ranges: list[dict[str, int]],
) -> dict[tuple[int, int], list[int]]:
    owners: dict[tuple[int, int], list[int]] = {}
    for item in ranges:
        owners.setdefault((item["start"], item["end"]), []).append(item["anchor"])
    return owners

def extract_target_local_image_list(
    page_html: str, note_id: str
) -> dict[str, Any] | None:
    note_ranges = target_note_object_ranges(page_html, note_id)
    if not note_ranges:
        return None

    arrays = find_image_list_arrays_with_positions(page_html)
    owner_ranges = object_ranges_at_positions(
        page_html, (item["key_start"] for item in arrays)
    )
    owner_anchors = target_owner_anchors(note_ranges)
    candidates: list[dict[str, Any]] = []
    for array in arrays:
        owner = owner_ranges.get(array["key_start"])
        anchors = (
            owner_anchors.get((owner["start"], owner["end"]))
            if owner
            else None
        )
        if not anchors:
            continue
        distance = min(abs(array["start"] - anchor) for anchor in anchors)
        parsed = parse_json_like(array["text"])
        if isinstance(parsed, list):
            images = choose_image_assets(parsed)
        else:
            images = [
                {
                    "sourceUrl": source_url,
                    "livePhoto": False,
                    "liveVideo": None,
                }
                for source_url in unique_keep_order(
                    XHS_IMAGE_PATTERN.findall(array["text"])
                )
                if is_direct_image_url(source_url)
            ]
        if images:
            candidates.append({"distance": distance, "images": images})

    if not candidates:
        return None
    candidates.sort(key=lambda item: (item["distance"], -len(item["images"])))
    return {"images": candidates[0]["images"], "title": ""}

def find_video_objects_with_positions(text: str) -> list[dict[str, Any]]:
    objects: list[dict[str, Any]] = []
    pattern = re.compile(r'["\']video["\']\s*:\s*\{')
    for match in pattern.finditer(text):
        start = text.find("{", match.start())
        if start < 0:
            continue
        balanced = extract_balanced_structure(text, start, "{", "}")
        if balanced:
            object_text, end = balanced
            objects.append(
                {
                    "key_start": match.start(),
                    "start": start,
                    "end": end,
                    "text": object_text,
                }
            )
    return objects

def extract_target_local_video_streams(
    page_html: str, note_id: str
) -> list[dict[str, Any]]:
    note_ranges = target_note_object_ranges(page_html, note_id)
    if not note_ranges:
        return []

    objects = find_video_objects_with_positions(page_html)
    owner_ranges = object_ranges_at_positions(
        page_html, (item["key_start"] for item in objects)
    )
    owner_anchors = target_owner_anchors(note_ranges)
    candidates: list[dict[str, Any]] = []
    for item in objects:
        owner = owner_ranges.get(item["key_start"])
        anchors = (
            owner_anchors.get((owner["start"], owner["end"]))
            if owner
            else None
        )
        if not anchors:
            continue
        distance = min(abs(item["start"] - anchor) for anchor in anchors)
        parsed = parse_json_like(item["text"])
        if not isinstance(parsed, dict):
            continue
        videos = extract_video_streams_from_note({"video": parsed})
        if videos:
            candidates.append({"distance": distance, "videos": videos})

    if not candidates:
        return []
    candidates.sort(key=lambda item: (item["distance"], -len(item["videos"])))
    return candidates[0]["videos"]

def extract_primary_meta_video(page_html: str) -> dict[str, Any] | None:
    meta_pattern = re.compile(r"<meta\b[^>]*>", re.I)
    content_pattern = re.compile(r"\bcontent\s*=\s*([\"'])(.*?)\1", re.I)
    key_pattern = re.compile(r"\b(?:property|name)\s*=\s*([\"'])(.*?)\1", re.I)

    for tag_match in meta_pattern.finditer(page_html):
        tag = tag_match.group(0)
        content_match = content_pattern.search(tag)
        key_match = key_pattern.search(tag)
        content = content_match.group(2) if content_match else ""
        key = key_match.group(2).lower() if key_match else ""
        if key not in VIDEO_META_KEYS:
            continue
        normalized = normalize_image_url(content)
        if is_xhs_video_url(normalized):
            return {
                "url": normalized,
                "backupUrls": [],
                "codec": "h264",
                "width": 0,
                "height": 0,
                "bitrate": 0,
                "size": 0,
                "qualityType": "meta",
                "source": "primary-meta",
            }
    return None

def extract_primary_meta_image(page_html: str) -> str | None:
    meta_pattern = re.compile(r"<meta\b[^>]*>", re.I)
    content_pattern = re.compile(r"\bcontent\s*=\s*([\"'])(.*?)\1", re.I)
    key_pattern = re.compile(r"\b(?:property|name)\s*=\s*([\"'])(.*?)\1", re.I)
    allowed_keys = {"og:image", "twitter:image", "twitter:image:src"}

    for tag_match in meta_pattern.finditer(page_html):
        tag = tag_match.group(0)
        content_match = content_pattern.search(tag)
        key_match = key_pattern.search(tag)
        content = content_match.group(2) if content_match else ""
        key = key_match.group(2).lower() if key_match else ""
        if key not in allowed_keys:
            continue
        normalized = normalize_image_url(content)
        if is_xhs_image_url(normalized):
            return normalized
    return None

def extract_original_asset_token(url: str) -> str | None:
    normalized = normalize_image_url(url)
    parsed = urlparse(normalized)
    if not is_xhs_image_url(normalized):
        return None

    parts: list[str] = []
    for part in (value for value in parsed.path.split("/") if value):
        if re.search(r"%(?![0-9A-Fa-f]{2})", part):
            return None
        try:
            parts.append(unquote(part, errors="strict"))
        except UnicodeDecodeError:
            return None
    if not parts:
        return None

    if parsed.netloc.lower() == "ci.xiaohongshu.com":
        parts[-1] = parts[-1].split("!", 1)[0]
        return "/".join(parts).strip("/") or None

    if len(parts) >= 3 and re.fullmatch(r"\d{10,14}", parts[0]):
        parts = parts[2:]
    if not parts:
        return None
    parts[-1] = parts[-1].split("!", 1)[0]
    return "/".join(parts).strip("/") or None

def validate_asset_token(token: Any) -> bool:
    return bool(
        isinstance(token, str)
        and 1 <= len(token) <= 400
        and not token.startswith("/")
        and ".." not in token
        and "\\" not in token
        and re.fullmatch(r"[A-Za-z0-9/_~.\-]+", token)
    )

def build_no_watermark_url(token: str) -> str:
    if not validate_asset_token(token):
        raise XhsError("图片资源标识无效。")
    encoded = "/".join(quote(part, safe="-_.~") for part in token.split("/"))
    return f"https://ci.xiaohongshu.com/{encoded}?imageView2/format/jpg"

def extract_page_title(page_html: str) -> str:
    patterns = (
        re.compile(
            r"<meta\b[^>]*(?:property|name)=[\"']og:title[\"'][^>]*"
            r"content=[\"'](.*?)[\"'][^>]*>",
            re.I,
        ),
        re.compile(
            r"<meta\b[^>]*content=[\"'](.*?)[\"'][^>]*"
            r"(?:property|name)=[\"']og:title[\"'][^>]*>",
            re.I,
        ),
        re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.S),
    )
    for pattern in patterns:
        match = pattern.search(page_html)
        if match and match.group(1):
            value = re.sub(r"<[^>]+>", "", match.group(1).strip())
            return html_lib.unescape(value)[:120]
    return "小红书图片"

def convert_image_assets(image_assets: Iterable[Any]) -> list[dict[str, Any]]:
    images: list[dict[str, Any]] = []
    for asset in image_assets:
        source_url = (
            asset.get("sourceUrl")
            if isinstance(asset, dict)
            else asset
        )
        if not isinstance(source_url, str):
            continue
        token = extract_original_asset_token(source_url)
        if not token or not validate_asset_token(token):
            continue
        images.append(
            {
                "token": token,
                "url": build_no_watermark_url(token),
                "livePhoto": bool(
                    asset.get("livePhoto") if isinstance(asset, dict) else False
                ),
                "liveVideo": (
                    asset.get("liveVideo") if isinstance(asset, dict) else None
                ),
            }
        )
    return images

def parse_note_html(page_html: str, note_id: str) -> dict[str, Any]:
    if not note_id:
        return {
            "title": extract_page_title(page_html),
            "content": "",
            "images": [],
            "videos": [],
            "strategy": "missing-note-id",
        }

    exact = select_exact_note_from_states(page_html, note_id)
    if exact:
        return {
            "title": exact["title"] or extract_page_title(page_html),
            "content": exact["content"],
            "images": convert_image_assets(exact["images"])[:50],
            "videos": prepare_video_results(exact["videos"]),
            "strategy": "exact-initial-state",
        }

    local_images = extract_target_local_image_list(page_html, note_id)
    local_videos = extract_target_local_video_streams(page_html, note_id)
    if local_images or local_videos:
        return {
            "title": (
                local_images.get("title", "") if local_images else ""
            ) or extract_page_title(page_html),
            "content": "",
            "images": convert_image_assets(
                local_images.get("images", []) if local_images else []
            )[:50],
            "videos": prepare_video_results(local_videos),
            "strategy": (
                "note-id-local-media"
                if local_images and local_videos
                else "note-id-local-image-list"
                if local_images
                else "note-id-local-video"
            ),
        }

    primary_image = extract_primary_meta_image(page_html)
    primary_video = extract_primary_meta_video(page_html)
    return {
        "title": extract_page_title(page_html),
        "content": "",
        "images": convert_image_assets([primary_image]) if primary_image else [],
        "videos": prepare_video_results([primary_video]) if primary_video else [],
        "strategy": (
            "primary-meta-media"
            if primary_image and primary_video
            else "primary-meta-cover"
            if primary_image
            else "primary-meta-video"
            if primary_video
            else "not-found"
        ),
    }

